# Generated by Django 3.0.7 on 2020-06-16 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0002_investor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_to_invest', models.BigIntegerField()),
                ('expected_interest', models.IntegerField()),
                ('date_of_invest', models.DateTimeField()),
                ('withdraw_date', models.DateTimeField()),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='investor.Investor')),
            ],
            options={
                'verbose_name': 'Invest',
                'verbose_name_plural': 'Invests',
            },
        ),
    ]
