# Generated by Django 3.0.7 on 2020-06-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0004_auto_20200616_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='account_number',
            field=models.BigIntegerField(),
        ),
    ]
