# Generated by Django 3.0.7 on 2020-06-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0005_auto_20200616_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='invest',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invest',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
