# Generated by Django 3.0.7 on 2020-06-17 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0007_auto_20200616_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invest',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investor.Investor'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='bank_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investor.Bank'),
        ),
    ]
