# Generated by Django 3.0.7 on 2020-06-18 09:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0010_notification_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='invest',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
