# Generated by Django 3.0.7 on 2020-06-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0011_invest_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='has_download',
            field=models.BooleanField(default=False),
        ),
    ]
