# Generated by Django 3.0.7 on 2020-06-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0012_notification_has_download'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFSignImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIELDNAME', models.ImageField(upload_to='upload')),
            ],
        ),
    ]
