# Generated by Django 3.0.7 on 2020-06-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0013_pdfsignimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfsignimage',
            name='name',
            field=models.CharField(default='PDF Sign Image', max_length=100),
            preserve_default=False,
        ),
    ]
