# Generated by Django 3.0.7 on 2020-06-22 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0014_pdfsignimage_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfsignimage',
            old_name='FIELDNAME',
            new_name='image',
        ),
    ]
