# Generated by Django 3.0.7 on 2020-06-22 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0015_auto_20200622_0916'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PDFSignImage',
        ),
    ]
