# Generated by Django 3.0.7 on 2020-06-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0017_auto_20200624_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.ManyToManyField(blank=True, null=True, to='investor.Attachment'),
        ),
    ]
