# Generated by Django 3.0.7 on 2020-06-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0019_remove_message_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_view',
            field=models.BooleanField(default=False),
        ),
    ]
