# Generated by Django 3.0.7 on 2020-06-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0020_message_is_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_view',
            new_name='is_view_admin',
        ),
        migrations.AddField(
            model_name='message',
            name='is_view_investor',
            field=models.BooleanField(default=False),
        ),
    ]
