# Generated by Django 3.0.7 on 2020-06-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0021_auto_20200624_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popup_type', models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('info', 'info'), ('light', 'light'), ('dark', 'dark')], max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('second_paragraph', models.TextField(blank=True, null=True)),
                ('third_paragraph', models.TextField(blank=True, null=True)),
                ('button_text', models.CharField(default='How to Join', max_length=100)),
                ('button_link', models.CharField(max_length=100)),
                ('button_type', models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('info', 'info'), ('light', 'light'), ('dark', 'dark')], max_length=100)),
            ],
        ),
    ]
