# Generated by Django 3.0.7 on 2020-06-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0022_popup'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
