# Generated by Django 3.0.7 on 2020-06-30 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0023_popup_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='popup',
            name='button_type',
            field=models.CharField(choices=[('', 'Select Type'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark')], max_length=100),
        ),
        migrations.AlterField(
            model_name='popup',
            name='popup_type',
            field=models.CharField(choices=[('', 'Select Type'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark')], max_length=100),
        ),
    ]
