# Generated by Django 3.0.7 on 2020-07-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0024_auto_20200630_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='invest',
            name='reinvest_status',
            field=models.BooleanField(default=False),
        ),
    ]
