# Generated by Django 3.0.7 on 2020-07-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0025_invest_reinvest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invest',
            name='widthdrawn_status',
            field=models.BooleanField(default=False),
        ),
    ]
