# Generated by Django 3.0.7 on 2020-07-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0026_invest_widthdrawn_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invest',
            name='delete_status',
            field=models.BooleanField(default=False),
        ),
    ]
