# Generated by Django 3.0.7 on 2020-07-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0027_invest_delete_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Termscondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=300)),
                ('page_content', models.TextField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
