# Generated by Django 3.0.7 on 2020-07-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0028_termscondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='invest',
            name='email_send_status',
            field=models.BooleanField(default=False),
        ),
    ]
