# Generated by Django 3.0.7 on 2020-07-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0029_invest_email_send_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
