# Generated by Django 3.0.7 on 2020-07-09 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0031_editor_interest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='interest',
            options={},
        ),
    ]
