# Generated by Django 3.0.7 on 2020-07-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0033_auto_20200710_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='password',
            field=models.CharField(default='asdfjasldkfj', max_length=50),
        ),
    ]
