# Generated by Django 3.0.7 on 2020-07-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0034_auto_20200710_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
