# Generated by Django 3.0.7 on 2020-07-11 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0036_access_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='investor.Role'),
            preserve_default=False,
        ),
    ]
