# Generated by Django 3.0.7 on 2020-07-13 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0037_editor_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='access',
            new_name='role_access',
        ),
    ]
